### ISSUE TITLE
min-height?

### ISSUE THREAD

**Issue by joshuarrr** [mvasin/react-div-100vh#1]
Thanks for sharing this component! 

For my use I needed to change `node.style.height = window.innerHeight + 'px';` to `node.style.minHeight = window.innerHeight + 'px';`. I don't know how to do this but it seems like passing that down as a prop might be useful?

**Comment by mvasin** [comment]
Hi, Joshua! I'm glad you found it useful.

I think we can pass the component a style object like we would to a normal div, and pass most of it through as is to the inner div, except values in `vh` units. Those we will fix by passing the pixels instead.

Or even better, we can come up with our own unit – 'rvh' (real viewport height). We will suppose that if people supply `/^\d+rvh$/` as a value to any key in style object, they mean it.

Do you like the idea? Would you like to make a PR?

**Comment by mvasin** [comment]
Closed by #2.
