### ISSUE TITLE
Wrong height when used in iOS WKWebView

### ISSUE THREAD

**Issue by akinnee** [mvasin/react-div-100vh#11]
Setting 678 but the window is 818.
<img width="159" alt="screen shot 2018-11-28 at 12 50 07 pm" src="https://user-images.githubusercontent.com/3019562/49171295-39d1ad80-f30c-11e8-82f7-27a5ded63724.png">
<img width="140" alt="screen shot 2018-11-28 at 12 50 18 pm" src="https://user-images.githubusercontent.com/3019562/49171296-39d1ad80-f30c-11e8-800e-e811177985ee.png">

**Comment by bignimbus** [comment]
@akinnee Can you provide the source code as well?

**Comment by akinnee** [comment]
I think the webview is not emitting a resize event. I was able to fix it by manually calling updateStyle after the webview is shown.
