### ISSUE TITLE
Build Failed with create-react-app

### ISSUE THREAD

**Issue by siriwatknp** [mvasin/react-div-100vh#12]
this is my package.json
```
"react-scripts": "1.1.5",
"react-div-100vh": "^0.3.2"
```

I got this error after run `yarn build`

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/jest-get-type/build/index.js:14 

Read more here: http://bit.ly/2tRViJ9

```

**Comment by mvasin** [comment]
I was not able to reproduce it with the latest CRA. Update `react-scripts` to the latest version, it should be [pretty easy](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html#updating-a-project-to-create-react-app-20).
