### ISSUE TITLE
Bug with mobile chrome

### ISSUE THREAD

**Issue by maystrenkoYurii** [mvasin/react-div-100vh#13]
Bug with mobile chrome after change orientation not recalculated correct height. Sorry of my English

**Comment by mvasin** [comment]
Hi @maystrenkoYurii and thanks for the report, I'll look into it after New Year holidays.

**Comment by ericfrank** [comment]
@maystrenkoYurii @mvasin I've added this hack in my code to get around the issue until it's been patched:

```
const resize = () => window.dispatchEvent(new Event('resize'));

window.addEventListener('orientationchange', () => {
  [250, 500, 750].forEach(time => setTimeout(resize, time));
}, false);
```

**Comment by mvasin** [comment]
PR #22 (which is now live in `react-div-100vh@0.3.5`) addresses the Chrome orientation change bug, so I'm closing this issue. Please test as well and in case something pops up, feel free to reopen this issue or open a new one.
