### ISSUE TITLE
Could not find a declaration file for module 'react-div-100vh

### ISSUE THREAD

**Issue by eric-personal** [mvasin/react-div-100vh#16]
I'm using gatsby and running into this import error ? 
Anyway to get round this. 

`Could not find a declaration file for module 'react-div-100vh'. 'path/node_modules/react-div-100vh/lib/index.js' implicitly has an 'any' type.`

Unfortunately my project is way too large to break down into a example.

**Comment by mvasin** [comment]
I plan to rewrite this library in typescript, so there will be ts declarations. I can’t reveal any deadlines though, as I’m quite busy at work.

**Comment by nerdyman** [comment]
As a temporary workaround you can add the following to a declaration module (`.d.ts`).

```
declare module 'react-div-100vh' {
	export default function(props: React.Props): React.Element<React.Props>;
}
```
