### ISSUE TITLE
0.3.3 is broken

### ISSUE THREAD

**Issue by schneidmaster** [mvasin/react-div-100vh#17]
Hi there! It looks like 0.3.3 is missing the `lib/` folder in the tarball on npm. Here's what it looks like installed in the `node_modules` of my project:

<img width="1061" alt="Screenshot 2019-04-28 12 00 16" src="https://user-images.githubusercontent.com/1896112/56866935-44709b80-69ad-11e9-8543-1dfc305ac551.png">

Did you maybe forget to run the `lib` script before publishing? 🙂

**Comment by mvasin** [comment]
Hi @schneidmaster! Thanks for rising the issue. Manual publishing process leaves a lot to be desired (I definitely look forward to automate it).

Should be fixed in 0.3.4.
