### ISSUE TITLE
Zoom on iOS Safari (Iphone 8, iOS 13)

### ISSUE THREAD

**Issue by patotoma** [mvasin/react-div-100vh#24]
Zooming breaks the layout on demo page (https://react-div-100vh.netlify.com) on iOS Safari:

![Image from iOS](https://user-images.githubusercontent.com/3104587/69601837-1d17a500-1048-11ea-9240-5125b381ff18.png)

Expected would be to keep the same size as without zoom. On Android Chrome I see it working properly.

**Comment by mvasin** [comment]
Hi @patotoma!

https://react-div-100vh-git-switch-from-clientheight-to-in-07120a-vasin.vercel.app doesn't seem to have this issue (that's version `0.7.0-beta.1`), so I will close the issue if you don't mind.
![IMG_4288](https://user-images.githubusercontent.com/12434833/140663370-5883e6b9-75ae-433b-bffe-9d63911fddf7.PNG)
![IMG_4289](https://user-images.githubusercontent.com/12434833/140663373-612701bd-3e50-4b49-95d9-8fc665b76162.PNG)
