### ISSUE TITLE
React version compatibility

### ISSUE THREAD

**Issue by bignimbus** [mvasin/react-div-100vh#3]
First, thanks for creating this!

`createRef` is only [supported as of React 16.3](https://reactjs.org/docs/refs-and-the-dom.html#dont-overuse-refs), but the [peerDependencies](https://github.com/mvasin/react-div-100vh/blob/master/package.json#L17) show:

```
"react": ">15",
```

It probably makes sense to use the legacy `ref` callback implementation for the time being.  I can probably get a patch together reasonably quickly if you'd like.

**Comment by mvasin** [comment]
Resolved by #4
