### ISSUE TITLE
Website opened via Instagram browser has incorrect height

### ISSUE THREAD

**Issue by jdolinski1** [mvasin/react-div-100vh#52]
Websites using `react-div-100vh` opened via instagram browser (eg. linking the website from IG profile description) are rendered with wrong vertical height (the ig-browser bottom bar overlaps the content etc.).

**Comment by mvasin** [comment]
Thanks for reporting this, @jdolinski1! I'll have a look when time permits. In the meantime, help is welcome.

**Comment by jdolinski1** [comment]
@mvasin Sorry for confusion, i am sure this was occurring few weeks or months ago. Somehow i have just downloaded IG app on iOS, tried it, and this seem to have been fixed on IG side 🤔. Not sure about Android though.

**Comment by mvasin** [comment]
Alright, then I'm closing the issue. BTW I released this change https://github.com/mvasin/react-div-100vh/pull/74/files as `react-div-100vh@0.7.0-beta.1`, feel free to try it out.
