### ISSUE TITLE
Update height on device orientation change? 

### ISSUE THREAD

**Issue by devhims** [mvasin/react-div-100vh#55]
Hi @mvasin, how can we update the height as the orientation change from portrait to landscape and vice-versa when using  Chrome on iOS?  Although it seems like a pretty common scenrio, I couldn't find any related issues posted here. Can you please guide me?

**Comment by emrehayirci** [comment]
Hey @devhims it seems that this component attaches a resize function to the window.resize event, which supposed to fire on mobile screens too during orientation changes. So it should be resizing already

**Comment by mvasin** [comment]
Hi @devhims! I released this change https://github.com/mvasin/react-div-100vh/pull/74/files as `react-div-100vh@0.7.0-beta.1`. Can you try it out?

**Comment by mvasin** [comment]
Seems to be addressed in version `0.7.0`, please let me know if you still encounter the issue.
