### ISSUE TITLE
On entering a text field on safari a bunch of additional space is created at the bottom

### ISSUE THREAD

**Issue by stueynet** [mvasin/react-div-100vh#58]
When you focus into a text field on safari it causes a bunch of additional white space below the full height wrapper. Here are some screenshots. This was done on an ios simulator.

| Default | Focused with keyboard | Focused without keyboard
|-|-|-|
|<img width="483" alt="Screen Shot 2021-04-13 at 08 13 05" src="https://user-images.githubusercontent.com/1100677/114550743-89d91280-9c30-11eb-949c-3414f6dfdf30.png"> | <img width="490" alt="Screen Shot 2021-04-13 at 08 12 16" src="https://user-images.githubusercontent.com/1100677/114550751-8d6c9980-9c30-11eb-823d-b30d834154c0.png"> | <img width="487" alt="Screen Shot 2021-04-13 at 08 18 35" src="https://user-images.githubusercontent.com/1100677/114551104-f227f400-9c30-11eb-905b-0068a4a18cc9.png"> |

**Comment by stueynet** [comment]
Following up with an update. It appears if you disable the ios safari toolbar the behaviour is fine. 

<img width="476" alt="Screen Shot 2021-04-13 at 09 04 22" src="https://user-images.githubusercontent.com/1100677/114557022-403ff600-9c37-11eb-9747-49cadc3a4ff3.png">

**Comment by mvasin** [comment]
Hi, @stueynet and thanks for sharing.

I think I can reproduce the above on [the demo page](https://react-div-100vh.vercel.app): if I click into the input field and scroll till the bottom, and then pull again (as if trying to scroll further to the bottom), I see the URL bar at the top from slim turns to a regular height, and simultaneously white space adds up at the bottom.

But I see the same when I switch the radio button from "The <Div100vh> component" to "a regular <div style={{height: '100vh'}}>" component. So it doesn't seem to be an issue with this library, but rather a Safari issue. WDYT?

**Comment by stueynet** [comment]
> Hi, @stueynet and thanks for sharing.
> 
> 
> 
> I think I can reproduce the above on [the demo page](https://react-div-100vh.vercel.app): if I click into the input field and scroll till the bottom, and then pull again (as if trying to scroll further to the bottom), I see the URL bar at the top from slim turns to a regular height, and simultaneously white space adds up at the bottom.
> 
> 
> 
> But I see the same when I switch the radio button from "The <Div100vh> component" to "a regular <div style={{height: '100vh'}}>" component. So it doesn't seem to be an issue with this library, but rather a Safari issue. WDYT?

Yeah likely safari.
