### ISSUE TITLE
module error when building

### ISSUE THREAD

**Issue by MikeLundahl** [mvasin/react-div-100vh#6]
Getting this error when using webpack to build. Also using React 16.4.1

ERROR in ./~/react-div-100vh/lib/convertStyle/convertStyle.js
Module not found: Error: Can't resolve 'jest-get-type' in 'C:\projects\node_modules\react-div-100vh\lib\convertStyle'
 @ ./~/react-div-100vh/lib/convertStyle/convertStyle.js 9:42-66
 @ ./~/react-div-100vh/lib/convertStyle/index.js
 @ ./~/react-div-100vh/lib/Div100vh.js
 @ ./~/react-div-100vh/lib/index.js

**Comment by mvasin** [comment]
I have hopefully fixed the issue in version 0.3.1 (please confirm it), but I'd love to have steps to reproduce the problem for version 0.3.0, so I can add the case to the test suite.

**Comment by MikeLundahl** [comment]
I figured out what was causing the problem.. I disabled the UglifyJsPlugin plugin in webpack config. then it worked.

**Comment by mvasin** [comment]
Great. If you'll have an idea on what could be improved in the component code or build process, please share in form of a PR.

Can we close the issue now?

**Comment by MikeLundahl** [comment]
Yes. thanks!
