### ISSUE TITLE
`document.documentElement?.clientHeight` is not updating on latest iOS safari

### ISSUE THREAD

**Issue by ogroppo** [mvasin/react-div-100vh#73]
on iOS 15.0.2 when the footer slides down this rule breaks

https://github.com/mvasin/react-div-100vh/blob/master/packages/react-div-100vh/src/index.tsx#L49

because clientHeight is always the same, innerHeight seems to behave correctly

**Comment by mvasin** [comment]
Hi @ogroppo, thanks for the report! Would you like to create an MR?

**Comment by mvasin** [comment]
Hi @ogroppo! I released this change https://github.com/mvasin/react-div-100vh/pull/74/files as `react-div-100vh@0.7.0-beta.1`. Can you try it out?

**Comment by ogroppo** [comment]
Hi there! Apologies I had no time whatsoever even to contribute with this little change, anyway, it looks good on my devices ✅

**Comment by mvasin** [comment]
Perfect! I published the updated version under version `0.7.0`.
