### ISSUE TITLE
not working for me...

### ISSUE THREAD

**Issue by rchrdnsh** [mvasin/react-div-100vh#8]
I really want this to work, but I tried using it in my Gatsby JS app and it doesn't seem to be doing the job. Here is my layout code:

```
export default ({ children }) => (
  <Div100vh>
    <StaticQuery
      query={graphql`
        query {
          site {
            siteMetadata {
              title
            }
          }
        }
      `}
      render={data => (
        <AppLayout>
          <Navigation>
            <NavLink to={`/`}>
              <H3>{data.site.siteMetadata.title}</H3>
            </NavLink>
            <NavLink to={`/products`}>
              Products
            </NavLink>
            <NavLink to={`/features`}>
              Features
            </NavLink>
            <NavLink to={`/about`}>
              About Us
            </NavLink>
          </Navigation>
          {/* <PageTransition> */}
            <MainContent>
              {children}
            </MainContent>
          {/* </PageTransition> */}
        </AppLayout>
      )}
    />
  </Div100vh>
)
```
I tried putting the component around both the whole layout, including the <StaticQuery>, which did not work, and also the <AppLayout> Component, then tried running it on my iPhone, and neither worked for me. Is there anything about using this component I should know about? Has it ever been tested with a Gatsby App at all?

It would be awesome if this can work for me, as I've been dealing with this issue for over a year now, and it's no fun at all.

**Comment by mvasin** [comment]
Hi! I’ll be happy to look into it if you’ll provide a code example that I could actually run.

Ideally, an example should contain as little unrelated/repeating code as possible, in order to just highlight the issue. A dedicated github repo or a codesandbox link would do just fine.

**Comment by rchrdnsh** [comment]
hmmmm...I'll need to figure out how to make those things, as I'm new to using git and GitHub, and have never made a repo or sandbox before, but I will do that today and share it with you hopefully :-)

**Comment by mvasin** [comment]
Thank you! I'd love to make it work for you.

1) Can you please clarify what exactly is the expected outcome and what do you get instead?
2) You still make me parse a lot of stuff, please reduce the repo to the very essence of the problem.

**Comment by mvasin** [comment]
I close this due to inactivity. @rchrdnsh Feel free to reopen if you'll come up with a reproduction (as tiny as possible).

**Comment by rchrdnsh** [comment]
yeah, just haven't been able to get back around to this, but will ping you when I can make a really simple demo :-)
